<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="10458" started-at="2021-04-23T08:13:23Z" finished-at="2021-04-23T08:13:34Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="10458" started-at="2021-04-23T08:13:23Z" finished-at="2021-04-23T08:13:34Z">
      <class name="io.hetu.core.plugin.cloudface.TestFinal">
        <test-method status="PASS" signature="initTestFunctions()[pri:0, instance:io.hetu.core.plugin.cloudface.TestFinal@6e20b53a]" name="initTestFunctions" is-config="true" duration-ms="3455" started-at="2021-04-23T03:13:24Z" finished-at="2021-04-23T03:13:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTestFunctions -->
        <test-method status="PASS" signature="registerFunctions()[pri:0, instance:io.hetu.core.plugin.cloudface.TestFinal@6e20b53a]" name="registerFunctions" is-config="true" duration-ms="7" started-at="2021-04-23T03:13:27Z" finished-at="2021-04-23T03:13:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerFunctions -->
        <test-method status="FAIL" signature="TestSystem()[pri:0, instance:io.hetu.core.plugin.cloudface.TestFinal@6e20b53a]" name="TestSystem" duration-ms="6929" started-at="2021-04-23T03:13:27Z" finished-at="2021-04-23T03:13:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected only one result unique result, but got [0, -1] expected [1] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected only one result unique result, but got [0, -1] expected [1] but found [2]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at io.prestosql.operator.scalar.FunctionAssertions.selectUniqueValue(FunctionAssertions.java:308)
	at io.prestosql.operator.scalar.FunctionAssertions.selectSingleValue(FunctionAssertions.java:299)
	at io.prestosql.operator.scalar.FunctionAssertions.assertFunction(FunctionAssertions.java:262)
	at io.prestosql.operator.scalar.AbstractTestFunctions.assertFunction(AbstractTestFunctions.java:92)
	at io.hetu.core.plugin.cloudface.TestFinal.TestSystem(TestFinal.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSystem -->
        <test-method status="PASS" signature="destroyTestFunctions()[pri:0, instance:io.hetu.core.plugin.cloudface.TestFinal@6e20b53a]" name="destroyTestFunctions" is-config="true" duration-ms="1" started-at="2021-04-23T03:13:34Z" finished-at="2021-04-23T03:13:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- destroyTestFunctions -->
      </class> <!-- io.hetu.core.plugin.cloudface.TestFinal -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
